export const FIXED_DATE = new Date(2024, 5, 1); // month is 0 based

export const CHALLENGES_DESCRIPTIONS = [
	"Une photo d'un animal",
	"Le portrait",
	"Le noir et blanc",
	"La nature",
	"Le très petit",
	"Le très grand",
	"La musique",
	"La symétrie",
	"Le soleil",
	"Le temps",
	"Le mouvement",
	"L'immobile",
	"Le sport",
	"La vitesse",
	"La passion",
	"La couleur",
	"Raconte une histoire",
	"Le minimalisme",
	"Les reflets",
	"Les ombres",
	"La silhouette",
	"Le flou",
	"La vie",
	"L'amour",
	"La violence",
	"La douceur",
	"La texture",
	"L'architecture",
	"Les paysage",
	"Le ciel",
	"La nuit",
	"L'abstrait",
	"Le géométrique",
	"Le détail",
	"Le sourire",
	"Les yeux",
	"La vieillesse",
	"L'innocence",
	"Le bonheur",
	"Le mystère",
	"Monochrome",
	"La lumière",
	"La pluie",
	"Vintage",
	"Un objet : des escaliers",
	"Un objet : une montre",
	"La répétition",
	"Le chaos",
	"L'éphémère",
	"Le paradoxe",
	"La fragilité",
	"L'harmonie",
	"La dissonance",
	"L'équilibre",
];
